SELECT NOME FROM PAIS
ORDER BY NOME DESC

SELECT LOGRADOURO, CEP FROM ENDERECO e 
WHERE LOGRADOURO LIKE 'A%'

SELECT * FROM ENDERECO e 
WHERE CEP LIKE '%0'

SELECT * FROM ENDERECO e 
WHERE NUMERO >= 100

SELECT * FROM ENDERECO e 
WHERE LOGRADOURO LIKE 'Rua%'
ORDER BY CEP DESC 

SELECT ID_ENDERECO,MAX(ID_ENDERECO)
FROM ENDERECO e 
GROUP BY ID_ENDERECO 

SELECT ID_ENDERECO,COUNT(ID_ENDERECO)
FROM ENDERECO e 
GROUP BY ID_ENDERECO 