SELECT NOME FROM PAIS
ORDER BY NOME DESC

SELECT LOGRADOURO, CEP FROM ENDERECO e 
WHERE LOGRADOURO LIKE 'A%'

SELECT * FROM ENDERECO e 
WHERE CEP LIKE '%0'

SELECT * FROM ENDERECO e 
WHERE NUMERO >= 100

SELECT * FROM ENDERECO e 
WHERE LOGRADOURO LIKE 'Rua%'
ORDER BY CEP DESC 

SELECT ID_ENDERECO,COUNT(ID_ENDERECO)
FROM ENDERECO e 
GROUP BY ID_ENDERECO 

SELECT COUNT(*)
FROM ENDERECO 



UPDATE ENDERECO 
SET LOGRADOURO = 'Rua Leopoldo',
COMPLEMENTO = 'bl 20 ap 100'
WHERE ID_ENDERECO IN (2,3)


UPDATE ENDERECO 
SET NUMERO = 999999
WHERE ID_ENDERECO = 4

DELETE 
FROM ENDERECO e 
WHERE ID_ENDERECO  = (SELECT MAX(ID_ENDERECO) FROM ENDERECO e2)

DELETE
FROM ENDERECO e 
WHERE NUMERO = 999999

DELETE
FROM VEM_SER.ENDERECO e 

SELECT * FROM ENDERECO e;
SELECT * FROM BAIRRO b ;

