SELECT * FROM PESSOA p 
SELECT * FROM ENDERECO_PESSOA ep 
SELECT * FROM CONTATO c 
SELECT * FROM PESSOA_X_PESSOA_ENDERECO pxpe 

-- CROSS JOIN

SELECT p.nome,c.numero

FROM PESSOA p 

CROSS JOIN CONTATO c  
   
-- INNER JOIN
   
 SELECT p.nome,c.numero
 		
 	FROM PESSOA p 
 	INNER JOIN CONTATO c ON (p.ID_PESSOA = c.ID_CONTATO)
 	
 	
--- 3
 	SELECT p.nome, pxpe.*,ep.*
 	
 	FROM PESSOA p 
 	INNER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = pxpe.ID_PESSOA)
 	INNER JOIN ENDERECO_PESSOA ep ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO)
 	
--- 4
 	SELECT *
 	FROM PESSOA p 
 	INNER JOIN CONTATO c ON (p.ID_PESSOA = c.ID_CONTATO)
 	INNER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = pxpe.ID_PESSOA)
 	INNER JOIN ENDERECO_PESSOA ep ON (pxpe.ID_ENDERECO = ep.ID_ENDERECO)
 	
--- 5
 	
 	SELECT p.nome,c.numero
 	FROM PESSOA p 
 	LEFT JOIN CONTATO c ON (p.ID_PESSOA = c.ID_CONTATO)
 	
--- 6
 	
 	SELECT *
 	FROM PESSOA p 
 	LEFT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = pxpe.ID_PESSOA)
 	LEFT JOIN ENDERECO_PESSOA ep ON (pxpe.ID_ENDERECO = ep.ID_ENDERECO)
 	
--- 7
 	
 	SELECT p.NOME ,c.NUMERO ,c.DESCRICAO ,ep.LOGRADOURO ,ep.NUMERO ,ep.COMPLEMENTO ,ep.CIDADE ,ep.ESTADO 
 	FROM PESSOA p 
 	LEFT JOIN CONTATO c ON (p.ID_PESSOA = c.ID_CONTATO)
 	LEFT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = pxpe.ID_PESSOA)
 	LEFT JOIN ENDERECO_PESSOA ep ON (pxpe.ID_ENDERECO = ep.ID_ENDERECO)
 	
-------------------------------------------------------------------------------------------

   SELECT COUNT(PXPE.ID_ENDERECO),P.NOME
 	FROM PESSOA p 
 	LEFT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = pxpe.ID_PESSOA)
 	GROUP BY P.NOME
 
 	
   
   