CREATE TABLE VEM_SER.pais(
id_pais NUMBER PRIMARY KEY NOT NULL,
nome VARCHAR2(50)  UNIQUE NOT NULL
);

CREATE TABLE VEM_SER.ESTADO(
id_estado NUMBER PRIMARY KEY NOT NULL,
id_pais NUMBER NOT NULL,
nome VARCHAR2(50) NOT NULL ,
CONSTRAINT FK_ID_PAIS FOREIGN KEY ( ID_PAIS ) REFERENCES PAIS( ID_PAIS )
);

CREATE TABLE VEM_SER.CIDADE(
id_cidade NUMBER PRIMARY KEY NOT NULL,
id_estado NUMBER NOT NULL,
nome VARCHAR2(50) NOT NULL,
CONSTRAINT FK_ID_ESTADO FOREIGN KEY ( ID_ESTADO ) REFERENCES ESTADO( ID_ESTADO )
);

CREATE TABLE VEM_SER.BAIRRO(
id_bairro NUMBER PRIMARY KEY NOT NULL,
id_cidade NUMBER NOT NULL,
id_estado NUMBER NOT NULL,
nome VARCHAR2(50) NOT NULL,
CONSTRAINT FK_ID_CIDADE FOREIGN KEY ( ID_CIDADE ) REFERENCES CIDADE( ID_CIDADE ),
CONSTRAINT FK_BAIRRO_ESTADO FOREIGN KEY ( ID_ESTADO ) REFERENCES ESTADO( ID_ESTADO )
);

CREATE TABLE VEM_SER.ENDERECO(
id_endereco NUMBER PRIMARY KEY NOT NULL,
id_bairro NUMBER NOT NULL,
id_cidade NUMBER NOT NULL,
logradouro VARCHAR2(255) NOT NULL,
numero NUMBER NOT NULL,
complemento VARCHAR2(100),
cep CHAR (9) NOT NULL,
CONSTRAINT FK_ID_BAIRRO FOREIGN KEY ( ID_BAIRRO ) REFERENCES BAIRRO( ID_BAIRRO ),
CONSTRAINT FK_CIDADE_BAIRRO FOREIGN KEY ( ID_CIDADE ) REFERENCES CIDADE( ID_CIDADE )
);

DROP TABLE VEM_SER.ENDERECO 
DROP TABLE VEM_SER.BAIRRO 
DROP TABLE VEM_SER.CIDADE 
DROP TABLE VEM_SER.ESTADO 
DROP TABLE VEM_SER.PAIS 

INSERT INTO VEM_SER.PAIS 
(ID_PAIS,NOME)
VALUES(VEM_SER.seq_pais.nextval,'BRASIL');

SELECT * FROM PAIS


INSERT INTO VEM_SER.ESTADO 
(ID_ESTADO,ID_PAIS,NOME)
VALUES ()

DELETE FROM VEM_SER.PAIS

CREATE SEQUENCE VEM_SER.seq_pais
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE VEM_SER.seq_estado
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE VEM_SER.seq_cidade
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE VEM_SER.seq_bairro
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE VEM_SER.seq_endereco
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

--ESTADOS DO BRASIL

INSERT INTO VEM_SER.ESTADO
(ID_ESTADO,ID_PAIS,NOME)
VALUES(VEM_SER.seq_estado.nextval,1,'CEARA');

INSERT INTO VEM_SER.ESTADO
(ID_ESTADO,ID_PAIS,NOME)
VALUES(VEM_SER.seq_estado.nextval,1,'RIO GRANDE DO SUL');

-- ESTADOS DA ARGENTINA

INSERT INTO VEM_SER.ESTADO
(ID_ESTADO,ID_PAIS,NOME)
VALUES(VEM_SER.seq_estado.nextval,2,'PROVINCIA DE BUENOS AIRES');

INSERT INTO VEM_SER.ESTADO
(ID_ESTADO,ID_PAIS,NOME)
VALUES(VEM_SER.seq_estado.nextval,2,'ENTRE RIOS');

-- CIDADE DE BUENOS AIRES

INSERT INTO VEM_SER.CIDADE 
(ID_CIDADE,ID_ESTADO,NOME)
VALUES(VEM_SER.seq_cidade.nextval,4,'LA PLATA');

-- CIDADE DO CEARA

INSERT INTO VEM_SER.CIDADE 
(ID_CIDADE,ID_ESTADO,NOME)
VALUES(VEM_SER.seq_cidade.nextval,2,'FORTALEZA')

-- CIDADE DO RIO GRANDE DO SUL

INSERT INTO VEM_SER.CIDADE 
(ID_CIDADE,ID_ESTADO,NOME)
VALUES(VEM_SER.seq_cidade.nextval,3,'PORTO ALEGRE')

-- CIDAADE DE ENTRE RIOS

INSERT INTO VEM_SER.CIDADE 
(ID_CIDADE,ID_ESTADO,NOME)
VALUES(VEM_SER.seq_cidade.nextval,5,'PARANA')

-- BAIRRO DE LA PLATA

INSERT INTO VEM_SER.BAIRRO 
(ID_BAIRRO,ID_CIDADE,ID_ESTADO,NOME)
VALUES(VEM_SER.seq_bairro.nextval,1,4,'PLATA ARGENTINA')

-- BAIRRO DE FORTALEZA

INSERT INTO VEM_SER.BAIRRO 
(ID_BAIRRO,ID_CIDADE,ID_ESTADO,NOME)
VALUES(VEM_SER.seq_bairro.nextval,3,2,'ALDEOTA')

-- BAIRRO DE PORTO ALEGRE

INSERT INTO VEM_SER.BAIRRO 
(ID_BAIRRO,ID_CIDADE,ID_ESTADO,NOME)
VALUES(VEM_SER.seq_bairro.nextval,4,3,'ABERTA DOS MORROS')

-- BAIRRO DO PARANA

INSERT INTO VEM_SER.BAIRRO 
(ID_BAIRRO,ID_CIDADE,ID_ESTADO,NOME)
VALUES(VEM_SER.seq_bairro.nextval,5,5,'SAN AGUSTIN')

--endereços aldeota

INSERT INTO VEM_SER.ENDERECO 
(ID_ENDERECO,ID_BAIRRO,ID_CIDADE,LOGRADOURO,NUMERO,COMPLEMENTO,CEP)
VALUES(VEM_SER.seq_endereco.nextval,2,3,'Av. Barão de Studart', 1334, NULL, '601200-01')

INSERT INTO VEM_SER.ENDERECO 
(ID_ENDERECO,ID_BAIRRO,ID_CIDADE,LOGRADOURO,NUMERO,COMPLEMENTO,CEP)
VALUES(VEM_SER.seq_endereco.nextval,2,3,'Rua Silva Paulet', 1180, NULL, '60120-020')

-- endereços de aberta dos morros

INSERT INTO VEM_SER.ENDERECO 
(ID_ENDERECO,ID_BAIRRO,ID_CIDADE,LOGRADOURO,NUMERO,COMPLEMENTO,CEP)
VALUES(VEM_SER.seq_endereco.nextval,3,4,'Rua Hónorato Toniolo', 126, NULL, '917551-00')

INSERT INTO VEM_SER.ENDERECO 
(ID_ENDERECO,ID_BAIRRO,ID_CIDADE,LOGRADOURO,NUMERO,COMPLEMENTO,CEP)
VALUES(VEM_SER.seq_endereco.nextval,3,4,'Av. Celestino Bertolucci', 50, NULL, '91755-020')

--endereços de plata argentina

INSERT INTO VEM_SER.ENDERECO 
(ID_ENDERECO,ID_BAIRRO,ID_CIDADE,LOGRADOURO,NUMERO,COMPLEMENTO,CEP)
VALUES(VEM_SER.seq_endereco.nextval,1,1,'Calle', 59734, NULL,'B1900BTD')

INSERT INTO VEM_SER.ENDERECO 
(ID_ENDERECO,ID_BAIRRO,ID_CIDADE,LOGRADOURO,NUMERO,COMPLEMENTO,CEP)
VALUES(VEM_SER.seq_endereco.nextval,1,1,'C 10', 1312, NULL, 'B1900DOB')

--  ENDERECOS DE SAN AGUSTIN

INSERT INTO VEM_SER.ENDERECO 
(ID_ENDERECO,ID_BAIRRO,ID_CIDADE,LOGRADOURO,NUMERO,COMPLEMENTO,CEP)
VALUES(VEM_SER.seq_endereco.nextval,4,5,'Cnel. Caminos',1075, NULL,'E3100')

INSERT INTO VEM_SER.ENDERECO 
(ID_ENDERECO,ID_BAIRRO,ID_CIDADE,LOGRADOURO,NUMERO,COMPLEMENTO,CEP)
VALUES(VEM_SER.seq_endereco.nextval,4,5,'Gral. Galan' ,1802, NULL,'E3100')




SELECT ID_ESTADO, NOME FROM ESTADO e
SELECT * FROM CIDADE
SELECT * FROM BAIRRO b 
SELECT * FROM PAIS p 
SELECT * FROM BAIRRO b2 
SELECT * FROM ENDERECO e2 


